/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateUserRequest {
  email: string;
  name: string;
}

export interface DeleteUserRequest {
  id: number;
}

export interface GetUserRequest {
  id: number;
}

export interface UpdateUserRequest {
  email?: string;
  id: number;
  name?: string;
}
